# Generated by Django 5.0.6 on 2024-06-11 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='user_id',
        ),
        migrations.AddField(
            model_name='botuser',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('uz', 'Uzbek'), ('ru', 'Russian')], default='uz', max_length=2),
        ),
        migrations.AddField(
            model_name='botuser',
            name='latitude',
            field=models.DecimalField(decimal_places=9, default='0.0', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='botuser',
            name='longitude',
            field=models.DecimalField(decimal_places=9, default=0.0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='botuser',
            name='telegram_id',
            field=models.BigIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.BigIntegerField()),
                ('amount', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='api.botuser')),
            ],
        ),
    ]
