# Generated by Django 5.0.6 on 2024-06-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_remove_botuser_user_id_botuser_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='phone',
            field=models.CharField(default=1, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
