# Generated by Django 5.0.6 on 2024-06-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_phone_botuser_company_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botuser',
            old_name='company_employee_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='botuser',
            old_name='company_contact',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='employee_number',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='lifetime',
        ),
        migrations.AlterField(
            model_name='botuser',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('uz', 'Uzbek'), ('ru', 'Russian')], default='uz', max_length=2),
        ),
    ]
