# Generated by Django 5.0.6 on 2024-06-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_botuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='operator',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='botuser',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
