# Generated by Django 5.0.6 on 2024-06-30 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_name_botuser_company_employee_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('company_name', models.CharField(max_length=100)),
                ('employee_number', models.IntegerField()),
                ('lifetime', models.IntegerField()),
                ('company_employee_name', models.CharField(max_length=100)),
                ('company_contact', models.CharField(max_length=35)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian')], default='uz', max_length=2)),
            ],
        ),
        migrations.RenameField(
            model_name='botuser',
            old_name='company_contact',
            new_name='add_contact',
        ),
        migrations.RenameField(
            model_name='botuser',
            old_name='company_employee_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='employee_number',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='lifetime',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_id',
        ),
        migrations.AddField(
            model_name='botuser',
            name='contact',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='bot_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.botuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='bot_company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.botcompany'),
            preserve_default=False,
        ),
    ]
