# Generated by Django 5.0.6 on 2024-07-01 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_botcompany_language_remove_botuser_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='bot_company',
            new_name='bot_company_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='bot_user',
            new_name='bot_user_id',
        ),
    ]
