# Generated by Django 5.0.6 on 2024-07-02 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_bot_company_order_bot_company_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('product_name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=9, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=9, max_digits=12)),
                ('bot_company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_company', to='api.botcompany')),
            ],
        ),
        migrations.CreateModel(
            name='OrderUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('product_name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=9, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=9, max_digits=12)),
                ('bot_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to='api.botuser')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
