# Generated by Django 5.0.6 on 2024-06-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_order_product_order_product_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='longitude',
        ),
        migrations.AddField(
            model_name='order',
            name='latitude',
            field=models.DecimalField(decimal_places=9, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='longitude',
            field=models.DecimalField(decimal_places=9, default=1, max_digits=12),
            preserve_default=False,
        ),
    ]
