# Generated by Django 5.0.6 on 2024-07-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_ordercompany_orderuser_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='botcompany',
            name='language',
            field=models.CharField(choices=[('uz', "O'zbekcha"), ('ru', 'Русский')], default='uz', max_length=2),
        ),
        migrations.AddField(
            model_name='botuser',
            name='language',
            field=models.CharField(choices=[('uz', "O'zbekcha"), ('ru', 'Русский')], default='uz', max_length=2),
        ),
    ]
