# Generated by Django 5.0.6 on 2024-07-05 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_botcompany_language_botuser_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botcompany',
            name='language',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='language',
        ),
    ]
